@extends('errors.layout')
@section('title', 'Akses Ditolak')
@section('code', '403')
@section('icon', '🔒')
@section('title', 'Akses Ditolak')
@section('message', 'Maaf, Anda tidak memiliki izin untuk mengakses halaman ini. Silakan hubungi administrator jika Anda memerlukan akses.')
