@extends('errors.layout')
@section('title', 'Sesi Berakhir')
@section('code', '419')
@section('icon', '⏰')
@section('title', 'Sesi Berakhir')
@section('message', 'Sesi Anda telah berakhir. Silakan muat ulang halaman dan coba lagi.')
